SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `keeper`;

ALTER TABLE `book` CHANGE COLUMN `department` `book_department_id` INT NOT NULL DEFAULT 6;
ALTER TABLE `study` MODIFY COLUMN `information` VARCHAR(256) NOT NULL;
ALTER TABLE `study` MODIFY COLUMN `head_member_id` INT NOT NULL;
ALTER TABLE `study` MODIFY COLUMN `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

SET SQL_MODE=@OLD_SQL_MODE;