SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE `keeper`;

ALTER TABLE `member` CHANGE COLUMN `register_date` `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `member` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `book` CHANGE COLUMN `register_date` `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `book` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `equipment` CHANGE COLUMN `register_date` `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `equipment` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `friend` CHANGE COLUMN `register_date` `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `study` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `ctf_team` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `ctf_contest` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `ctf_challenge` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `survey` ADD COLUMN `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `survey` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);

ALTER TABLE `seminar` ADD COLUMN `register_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);
ALTER TABLE `seminar` ADD COLUMN `update_time` DATETIME NOT NULL DEFAULT (CURRENT_TIME);



DELIMITER $$

USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`member_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`member_BEFORE_UPDATE` BEFORE UPDATE ON `member` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`book_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`book_BEFORE_UPDATE` BEFORE UPDATE ON `book` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`equipment_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`equipment_BEFORE_UPDATE` BEFORE UPDATE ON `equipment` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`study_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`study_BEFORE_UPDATE` BEFORE UPDATE ON `study` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`ctf_contest_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`ctf_contest_BEFORE_UPDATE` BEFORE UPDATE ON `ctf_contest` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`ctf_team_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`ctf_team_BEFORE_UPDATE` BEFORE UPDATE ON `ctf_team` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`ctf_challenge_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`ctf_challenge_BEFORE_UPDATE` BEFORE UPDATE ON `ctf_challenge` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`survey_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`survey_BEFORE_UPDATE` BEFORE UPDATE ON `survey` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


USE `keeper`$$
DROP TRIGGER IF EXISTS `keeper`.`seminar_BEFORE_UPDATE` $$
USE `keeper`$$
CREATE DEFINER = CURRENT_USER TRIGGER `keeper`.`seminar_BEFORE_UPDATE` BEFORE UPDATE ON `seminar` FOR EACH ROW
BEGIN
	SET NEW.update_time = CURRENT_TIME;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;