-- MySQL Script generated by MySQL Workbench
-- Sun Jul 16 20:02:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

USE keeper;

-- -----------------------------------------------------
-- Table `keeper`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keeper`.`category` ;

CREATE TABLE IF NOT EXISTS `keeper`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `keeper`.`game_member_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `keeper`.`game_member_info` ;

CREATE TABLE IF NOT EXISTS `keeper`.`game_member_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `dice_per_day` INT NOT NULL DEFAULT 0,
  `roulette_per_day` INT NOT NULL DEFAULT 0,
  `lotto_per_day` INT NOT NULL DEFAULT 0,
  `baseball_per_day` INT NOT NULL DEFAULT 0,
  `last_play_time` DATETIME NULL DEFAULT (CURRENT_TIME),
  `dice_day_point` INT NOT NULL DEFAULT 0,
  `roulette_day_point` INT NOT NULL DEFAULT 0,
  `lotto_day_point` INT NOT NULL DEFAULT 0,
  `baseball_day_point` INT NOT NULL DEFAULT 0,
  `play_date` DATE NOT NULL DEFAULT (CURRENT_DATE),
  PRIMARY KEY (`id`),
  INDEX `fk_game_member_info_member1_idx` (`member_id` ASC) VISIBLE,
  UNIQUE INDEX `is_duplicated` (`member_id` ASC, `play_date` DESC) VISIBLE,
  CONSTRAINT `fk_game_member_info_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `keeper`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Data for table `keeper`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `keeper`;
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (1, 'virtual_category');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (101, '공지사항');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (102, '건의사항');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (103, '정보게시판');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (104, '자유게시판');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (105, '익명게시판');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (106, '졸업생게시판');
INSERT INTO `keeper`.`category` (`id`, `name`) VALUES (107, '시험게시판');

COMMIT;

-- -----------------------------------------------------
-- Data for table `keeper`.`member_job`
-- -----------------------------------------------------
START TRANSACTION;
USE `keeper`;

INSERT INTO `keeper`.`member_job` (`id`, `name`, `badge_thumbnail_id`) VALUES (12, 'ROLE_INFRA_전산관리자', 15);

COMMIT;